
Ski.create(sku: 1000, name: "Bent Chetler", price: 750, cost: 380, size: "184", category: "Powder", sex: "M", description: "The Atomic Bent Chetler 120 Skis are already the stuff of legend, and it goes well beyond the tales of Chris and Sage. This is a super light 120mm pow stick that defies standard definitions, but delivers the goods when the goods are delivered. Ideal in 3 feet of blower, especially when paired with a hybrid binding like the Shift in a place like Hokkaido. Dreamland.", image:"https://images.evo.com/imgp/zoom/197744/826829/atomic-bent-chetler-120-Bent Chetler-2022-.jpg", brand: "Atomic", count: 1)

Ski.create(sku: 1001, name: "ARW 116 VJJ UL", price: 799, cost: 410, size: "165", category: "Powder", sex: "M", description: "The Armada ARW 116 VJJ UL Skis are not just skis. They're enablers for your wildest powder day fever dreams. They float through Sierra Cement like they're blowing foam from the top of a glass of champagne, and they dance across blower pow like a sharp-clawed cat on a down comforter. They're nimble, like a needle trying to fix a comforter that's just been torn up by a sharp-clawed cat, and they're powerful, like the rebuke of someone whose champagne has just been wasted by blowing it on the floor. Release yourself to the limits of your imagination. The Armada ARW 116 VJJ UL Skis are the featherweight freedom factories of your future.", image:"https://images.evo.com/imgp/zoom/219366/917817/armada-arw-116-vjj-ul-skis-women-s-2023-.jpg", brand: "Armada", count: 5)

Ski.create(sku: 1002, name: "Bent 110", price: 700, cost: 325, size: "180", category: "Powder", sex: "M", description: "It's not for us to decide which skis are most deserving of your attention, but if the Atomic Bent 110 Skis don't appear on your shortlist, we're ready to stage an intervention. As the middle child of the newly expanded Atomic Bent family, the Bent 110s combine the freeride power of the 120s with the all mountain capability of the 100s. With floatation enhancing HRZN tech tips and tails and Atomic's snappy Light Woodcore, they deliver resort shredding, backcountry busting performance you can count on every. single. day. Topped off with Chris Benchetler's most fluid, creative artwork to date, the Bent 110s may be the last skis you ever need.", image:"https://images.evo.com/imgp/zoom/219399/896894/atomic-bent-110-skis-2023-.jpg", brand: "Atomic", count: 5)

Ski.create(sku: 1003, name: "Jeffery 110", price: 780, cost: 420, size: "186", category: "Freestyle", sex: "M", description: "The ON3P Jeffrey 110 Skis bring the same Jeffery construction you know and love to a wider platform that promises better stability and float on soft snow days. Along with the increased waist width, ON3P have bumped up the turn radius to create an altogether more aggressive platform, but the Jeffrey 110 continues to set the standard for freestyle skiers who like to throw down anywhere, anytime. Agile, versatile, and built ON3P tough, this might be the last ski you ever need.", image:"https://images.evo.com/imgp/zoom/210628/900179/on3p-jeffrey-110-skis-2022-.jpg", brand: "ON3P", count: 5)

Ski.create(sku: 1004, name: "Sick Day 104", price: 600, cost: 360, size: "179", category: "Freestyle", sex: "M", description: "You wanna take a sick day or have a sick day? With Line Skis Sick Day 104 Skis, you can do both. These sick sticks are a jack of all trades, and they're a blast to ride no matter the conditions. At 104mm underfoot, they offer enough float to take full advantage of those untouched zones, but they have plenty of power under the hood for firmer stuff thanks to full length Carbon Magic Fingers that boost stability and response. Pray for pow but don't get hung up on it, the Sick Day 104s certainly won't.", image:"https://images.evo.com/imgp/zoom/198436/817694/line-skis-sick-day-104-skis-2022-.jpg", brand: "Line", count:5)

Ski.create(sku: 1005, name: "Reckoner 112", price: 700, cost: 450, size: "184", category: "Freestyle", sex: "M", description: "A pow shape with a creative mindset, the K2 Reckoner 112 Skis are all about making fun happen on your terms. When your all-mountain style has evolved to include slashing, buttering and switching it up, the Reckoners allow you to express yourself to the limit. This fat all-mountain twin has become a Pacific Northwest classic in the short space of a year, and it should be on your short list if you're a free thinking, freshie hunting freerider.", image:"https://images.evo.com/imgp/zoom/201065/825029/k2-reckoner-112-skis-2022-.jpg", brand: "K2", count: 5)

Ski.create(sku: 1006, name: "Revolt 104", price: 550, cost: 250, size: "172", category: "Freestyle", sex: "M", description: "A new addition to the Völkl lineup this year, the Völkl Revolt 104 Skis slide in between the powder slashing Revolt 121 and the park jibbing Revolt 95. With a sturdy freestyle flex and a versatile 104 waist, this mid-sized Revolt fills the gap in the lineup and gives dynamic skiers a new weapon to play around the whole mountain on. It's got the park ski pop to boost backcountry booters and send it deep off cat track hits, but the trusted Völkl stability and sturdy platform to stomp landings and rip through spicier terrain in search of features.", image:"https://images.evo.com/imgp/zoom/183428/726981/volkl-revolt-104-skis-2022-.jpg", brand: "Volkl", count: 5)

Ski.create(sku: 1007, name: " Firebird Race Ti", price: 960, cost: 500, size: "166", category: "Race", sex: "M", description: "Looking to smoke your buds in your weekly Beer League sessions? Bored with sloppy Freeride skis when it goes two weeks with no new snow? Put some hard snow traction in your life with a pair of Blizzard Firebird Race Ti Skis + TPX12 Demo Bindings, and see what a detuned race ski can do on the groomers. With a 71mm waist and relatively short turn radius, these skis don't meet FIS specs, but they're much more versatile as well as socially responsible.", image:"https://images.evo.com/imgp/zoom/176871/851268/blizzard-firebird-race-ti-skis-tpx12-demo-bindings-2021-.jpg", brand: "Blizzard", count: 5)

Ski.create(sku: 1008, name: "GS FIS Race Dept", price: 1050, cost: 700, size: "195", category: "Race", sex: "M", description: "Bring your big, strong and fast game and be ready to ignore the screams of the safety patrol, the Blizzard GS FIS Race Dept Skis are here and they're not taking slow for an answer. This ski is from the era when GS skiers had legs the size of tree trunks and little regard for G forces - the 35 meter radius is definitely not for wussies, and neither is the FIS-minimum 195 centimeter length. If you've got the strength, size and skill to put these things on edge, you're in for the ride of your life.", image:"https://images.evo.com/imgp/zoom/210812/920167/blizzard-gs-fis-race-dept-skis-2017-.jpg", brand: "Blizzard", count:5)

Ski.create(sku: 1009, name: "Dictator 3.0", price: 720, cost: 450, size: "180", category: "Powder", sex: "M", description: "Rule the land with the Faction Dictator 3.0 Skis. A hard-charging ride for the skier who wants every day to be their best day, regardless of conditions. The Dictator 3.0 exercises its power in fresh powder, mashed potatoes, chunky chowder, corn — doesn't matter, the Dictator 3.0 rules all, laying its edge down whenever needed, regardless of political climate. The elliptical sidecut doesn't hook up at higher speeds and stops and turns on a dime., while the dual layer Titanal supporting a lively poplar core plus full sidewall construction arms the Dictator against snow shark uprisings and frozen chicken heads. The Faction Dictator 3.0 Skis are the supreme option for freeskiers eyeing up big lines, unafraid of getting their hands dirty in the process.", image:"https://images.evo.com/imgp/zoom/181933/733510/faction-dictator-3-0-skis-2022-.jpg", brand: "Faction", count:5)

Ski.create(sku: 1010, name: "Kore 105", price: 749, cost: 366, size: "177", category: "Freestyl", sex: "M", description: "The Head Kore 105 Skis have found a home in many an expert skier's quiver, and more often than not, they make most of the rest of that quiver obsolete. With tremendous edgehold, precise carving ability, and more than enough width and power to ski like a boss in variable and cut up new snow, the Kore 105 has gained enormous acceptance as a one-and-done tool for expert skiers. If you want to grab a ski in the morning with total confidence that it'll perform in any conditions, go with the Kore 105.", image:"https://images.evo.com/imgp/zoom/208271/832640/head-kore-105-skis-2022-.jpg", brand: "Head", count:5)

# APPAREL
Apparel.create(sku: 2000, name: "Trew Gear Cosmic Jacket", price: 200,  cost:100, size: "L", category: "Jacket", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/166505/769653/trew-gear-cosmic-jacket-.jpg", brand: "Trew", count:5)

Apparel.create(sku: 2000, name: "Trew Gear Cosmic Jacket", price: 200,  cost:100, size: "L", category: "Jacket", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/166505/769653/trew-gear-cosmic-jacket-.jpg", brand: "Trew", count: 5)

Apparel.create(sku: 2000, name: "Trew Gear Cosmic Jacket", price: 200, cost: 100, size: "L", category: "Jacket", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/166505/769653/trew-gear-cosmic-jacket-.jpg", brand: "Trew", count: 5)

Apparel.create(sku: 2000, name: "GORE-TEX 3L Breaker", price: 300, cost: 225, size: "L", category: "Jacket", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/195585/821522/burton-gore-tex-3l-breaker-jacket-.jpg", brand: "Burton", count: 5)

Apparel.create(sku: 2000, name: "GORE-TEX 3L Breaker", price: 300, cost: 225, size: "L", category: "Jacket", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/195585/821522/burton-gore-tex-3l-breaker-jacket-.jpg", brand: "Burton", count: 5)

Apparel.create(sku: 2000, name: "GORE-TEX 3L Breaker", price: 300, cost: 225, size: "L", category: "Jacket", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/195585/821522/burton-gore-tex-3l-breaker-jacket-.jpg", brand: "Burton", count: 5)

Apparel.create(sku: 2000, name: "Seymore Tall Pants", price: 350, cost: 230, size: "L", category: "Pants", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/204206/858847/the-north-face-seymore-tall-pants-.jpg", brand: "The North Face", count: 5)

Apparel.create(sku: 2000, name: "Seymore Tall Pants", price: 350, cost: 230, size: "L", category: "Pants", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/204206/858847/the-north-face-seymore-tall-pants-.jpg", brand: "The North Face", count: 5)

Apparel.create(sku: 2000, name: "Seymore Tall Pants", price: 350, cost: 230, size: "L", category: "Pants", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/204206/858847/the-north-face-seymore-tall-pants-.jpg", brand: "The North Face", count: 5)

Apparel.create(sku: 2000, name: "Seymore Tall Pants", price: 350, cost: 230, size: "L", category: "Pants", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/204206/858847/the-north-face-seymore-tall-pants-.jpg", brand: "The North Face" , count: 5)


# ACCESSORIES
Accessory.create(sku: 3000, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggle", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3000, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggle", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3000, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggle", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3000, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggle", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3000, name: "SmithSarek Ecocuir", price: 150, cost: 75, size: "L", category: "Gloves", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178633/725252/hestra-sarek-ecocuir-gloves-.jpg", brand: "Hestra", count: 5)

Accessory.create(sku: 3000, name: "Sarek Ecocuir", price: 150, cost: 75, size: "L", category: "Gloves", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178633/725252/hestra-sarek-ecocuir-gloves-.jpg", brand: "Hestra", count: 5)

Accessory.create(sku: 3000, name: "Smith I​/O MAG ", price: 150, cost: 75, size: "L", category: "Gloves", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178633/725252/hestra-sarek-ecocuir-gloves-.jpg", brand: "Hestra", count: 5)

Accessory.create(sku: 3000, name: "SPowder Town Beanie", price: 50, cost: 25, size: "L", category: "Hats", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/103037/857021/patagonia-powder-town-beanie-.jpg", brand: "Patagonia", count: 5)

Accessory.create(sku: 3000, name: "Powder Town Beanie", price: 50, cost: 25, size: "L", category: "Hats", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/103037/857021/patagonia-powder-town-beanie-.jpg", brand: "Patagonia", count: 5)

Accessory.create(sku: 3000, name: "Powder Town Beanie", price: 50, cost: 25, size: "L", category: "Hats", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/103037/857021/patagonia-powder-town-beanie-.jpg", brand: "Patagonia", count: 5)

# USERS
User.create(username: "jon", password:"jon", email:"jon@jon.com", admin: true)
puts "Seeding Complete"