
Ski.create(sku: 1000, name: "Bent Chetler", price: 750, cost: 380, size: "184", category: "Powder", sex: "Men", description: "The Atomic Bent Chetler 120 Skis are already the stuff of legend, and it goes well beyond the tales of Chris and Sage. This is a super light 120mm pow stick that defies standard definitions, but delivers the goods when the goods are delivered. Ideal in 3 feet of blower, especially when paired with a hybrid binding like the Shift in a place like Hokkaido. Dreamland.", image:"https://images.evo.com/imgp/zoom/197744/826829/atomic-bent-chetler-120-Bent Chetler-2022-.jpg", brand: "Atomic", count: 1)

Ski.create(sku: 1001, name: "ARW 116 VJJ UL", price: 799, cost: 410, size: "165", category: "Powder", sex: "Men", description: "The Armada ARW 116 VJJ UL Skis are not just skis. They're enablers for your wildest powder day fever dreams. They float through Sierra Cement like they're blowing foam from the top of a glass of champagne, and they dance across blower pow like a sharp-clawed cat on a down comforter. They're nimble, like a needle trying to fix a comforter that's just been torn up by a sharp-clawed cat, and they're powerful, like the rebuke of someone whose champagne has just been wasted by blowing it on the floor. Release yourself to the limits of your imagination. The Armada ARW 116 VJJ UL Skis are the featherweight freedom factories of your future.", image:"https://images.evo.com/imgp/zoom/219366/917817/armada-arw-116-vjj-ul-skis-women-s-2023-.jpg", brand: "Armada", count: 5)

Ski.create(sku: 1002, name: "Bent 110", price: 700, cost: 325, size: "180", category: "Powder", sex: "Men", description: "It's not for us to decide which skis are most deserving of your attention, but if the Atomic Bent 110 Skis don't appear on your shortlist, we're ready to stage an intervention. As the middle child of the newly expanded Atomic Bent family, the Bent 110s combine the freeride power of the 120s with the all mountain capability of the 100s. With floatation enhancing HRZN tech tips and tails and Atomic's snappy Light Woodcore, they deliver resort shredding, backcountry busting performance you can count on every. single. day. Topped off with Chris Benchetler's most fluid, creative artwork to date, the Bent 110s may be the last skis you ever need.", image:"https://images.evo.com/imgp/zoom/219399/896894/atomic-bent-110-skis-2023-.jpg", brand: "Atomic", count: 5)

Ski.create(sku: 1003, name: "Jeffery 110", price: 780, cost: 420, size: "186", category: "Freestyle", sex: "Men", description: "The ON3P Jeffrey 110 Skis bring the same Jeffery construction you know and love to a wider platform that promises better stability and float on soft snow days. Along with the increased waist width, ON3P have bumped up the turn radius to create an altogether more aggressive platform, but the Jeffrey 110 continues to set the standard for freestyle skiers who like to throw down anywhere, anytime. Agile, versatile, and built ON3P tough, this might be the last ski you ever need.", image:"https://images.evo.com/imgp/zoom/210628/900179/on3p-jeffrey-110-skis-2022-.jpg", brand: "ON3P", count: 5)

Ski.create(sku: 1004, name: "Sick Day 104", price: 600, cost: 360, size: "179", category: "Freestyle", sex: "Men", description: "You wanna take a sick day or have a sick day? With Line Skis Sick Day 104 Skis, you can do both. These sick sticks are a jack of all trades, and they're a blast to ride no matter the conditions. At 104mm underfoot, they offer enough float to take full advantage of those untouched zones, but they have plenty of power under the hood for firmer stuff thanks to full length Carbon Magic Fingers that boost stability and response. Pray for pow but don't get hung up on it, the Sick Day 104s certainly won't.", image:"https://images.evo.com/imgp/zoom/198436/817694/line-skis-sick-day-104-skis-2022-.jpg", brand: "Line", count:5)

Ski.create(sku: 1005, name: "Reckoner 112", price: 700, cost: 450, size: "184", category: "Freestyle", sex: "Men", description: "A pow shape with a creative mindset, the K2 Reckoner 112 Skis are all about making fun happen on your terms. When your all-mountain style has evolved to include slashing, buttering and switching it up, the Reckoners allow you to express yourself to the limit. This fat all-mountain twin has become a Pacific Northwest classic in the short space of a year, and it should be on your short list if you're a free thinking, freshie hunting freerider.", image:"https://images.evo.com/imgp/zoom/201065/825029/k2-reckoner-112-skis-2022-.jpg", brand: "K2", count: 5)

Ski.create(sku: 1006, name: "Revolt 104", price: 550, cost: 250, size: "172", category: "Freestyle", sex: "Men", description: "A new addition to the Völkl lineup this year, the Völkl Revolt 104 Skis slide in between the powder slashing Revolt 121 and the park jibbing Revolt 95. With a sturdy freestyle flex and a versatile 104 waist, this mid-sized Revolt fills the gap in the lineup and gives dynamic skiers a new weapon to play around the whole mountain on. It's got the park ski pop to boost backcountry booters and send it deep off cat track hits, but the trusted Völkl stability and sturdy platform to stomp landings and rip through spicier terrain in search of features.", image:"https://images.evo.com/imgp/zoom/183428/726981/volkl-revolt-104-skis-2022-.jpg", brand: "Volkl", count: 5)

Ski.create(sku: 1007, name: " Firebird Race Ti", price: 960, cost: 500, size: "166", category: "Race", sex: "Men", description: "Looking to smoke your buds in your weekly Beer League sessions? Bored with sloppy Freeride skis when it goes two weeks with no new snow? Put some hard snow traction in your life with a pair of Blizzard Firebird Race Ti Skis + TPX12 Demo Bindings, and see what a detuned race ski can do on the groomers. With a 71mm waist and relatively short turn radius, these skis don't meet FIS specs, but they're much more versatile as well as socially responsible.", image:"https://images.evo.com/imgp/zoom/176871/851268/blizzard-firebird-race-ti-skis-tpx12-demo-bindings-2021-.jpg", brand: "Blizzard", count: 5)

Ski.create(sku: 1008, name: "GS FIS Race Dept", price: 1050, cost: 700, size: "195", category: "Race", sex: "Men", description: "Bring your big, strong and fast game and be ready to ignore the screams of the safety patrol, the Blizzard GS FIS Race Dept Skis are here and they're not taking slow for an answer. This ski is from the era when GS skiers had legs the size of tree trunks and little regard for G forces - the 35 meter radius is definitely not for wussies, and neither is the FIS-minimum 195 centimeter length. If you've got the strength, size and skill to put these things on edge, you're in for the ride of your life.", image:"https://images.evo.com/imgp/zoom/210812/920167/blizzard-gs-fis-race-dept-skis-2017-.jpg", brand: "Blizzard", count:5)

Ski.create(sku: 1009, name: "Dictator 3.0", price: 720, cost: 450, size: "180", category: "Powder", sex: "Men", description: "Rule the land with the Faction Dictator 3.0 Skis. A hard-charging ride for the skier who wants every day to be their best day, regardless of conditions. The Dictator 3.0 exercises its power in fresh powder, mashed potatoes, chunky chowder, corn — doesn't matter, the Dictator 3.0 rules all, laying its edge down whenever needed, regardless of political climate. The elliptical sidecut doesn't hook up at higher speeds and stops and turns on a dime., while the dual layer Titanal supporting a lively poplar core plus full sidewall construction arms the Dictator against snow shark uprisings and frozen chicken heads. The Faction Dictator 3.0 Skis are the supreme option for freeskiers eyeing up big lines, unafraid of getting their hands dirty in the process.", image:"https://images.evo.com/imgp/zoom/181933/733510/faction-dictator-3-0-skis-2022-.jpg", brand: "Faction", count:5)

Ski.create(sku: 1010, name: "Kore 105", price: 749, cost: 366, size: "177", category: "Freestle", sex: "Men", description: "The Head Kore 105 Skis have found a home in many an expert skier's quiver, and more often than not, they make most of the rest of that quiver obsolete. With tremendous edgehold, precise carving ability, and more than enough width and power to ski like a boss in variable and cut up new snow, the Kore 105 has gained enormous acceptance as a one-and-done tool for expert skiers. If you want to grab a ski in the morning with total confidence that it'll perform in any conditions, go with the Kore 105.", image:"https://images.evo.com/imgp/zoom/208271/832640/head-kore-105-skis-2022-.jpg", brand: "Head", count:5)

Ski.create(sku: 1011, name: "Pandora 94", price: 499, cost: 300, size: "165", category: "Freestle", sex: "Women", description: "The Line Skis Pandora 94 Skis are the perfect all mountain sticks for ladies who want to make the most of every minute in the mountains. They'll have you churning up crud, bombing down groomers, and linking deep turns with ease whenever a fresh blanket presents itself. With Magic Finger Carbon Filaments and all around lightweight build, the Line Skis Pandora 94 Skis offer an unmatched weight-to-performance ratio to keep you spinning lifts longer than you ever thought possible.", image:"https://images.evo.com/imgp/zoom/197210/792961/line-skis-pandora-94-skis-women-s-2022-.jpg", brand: "Line", count:5)

# APPAREL
Apparel.create(sku: 2000, name: "Trew Gear Cosmic Jacket", price: 200,  cost:100, size: "Large", category: "Jackets", sex: "M", description: "The Armada Grands 3L Jacket gives off earth tone vibes in a sick protective shell. Offering 15k/15k of breathable, waterproof protection, this outer layer was made to take anything you throw at it. Durable recycled canvas brushes off tree scrapes and early-season snags. Lyrca wrist gaiters, a jacket to pants interface, and a stretchy powder skirt keeps moisture from getting inside the cozy zone. From park laps to big sends, the Armada Grands 3L Jacket is ready for whatever you have planned.", image:"https://images.evo.com/imgp/zoom/158777/655227/armada-resolution-gore-tex-3l-jacket-women-s-.jpg", brand: "Armada", count:5)



Apparel.create(sku: 2001, name: "Resolution GORE-TEX 3L ", price: 499,  cost: 266, size: "Medium", category: "Jackets", sex: "Woman", description: "Join the Resolution Revolution and step up to 3L GORE-TEX protection that's as outstanding as the Armada skis you love. 100% seam sealed and ready for the wet with GORE's outstanding waterproof breathable performance and the ultra comfortable C-Knit™ nylon backer, the Armada Resolution GORE-TEX 3L Jacket leaves other high end coats in its dust when the weather turns nasty.", image:"https://images.evo.com/imgp/zoom/158777/655227/armada-resolution-gore-tex-3l-jacket-women-s-.jpg", brand: "Armada", count: 5)



Apparel.create(sku: 2002, name: "Haydon 3L GORE-TEX", price: 499, cost: 288, size: "Medium", category: "Jackets", sex: "Men", description: "For when the going gets tough! The Armada Haydon 3L GORE-TEX Jacket is geared up with premium tech and features for optimal on-mountain performance. The GORE-TEX membrane makes light work of moisture management - built for the rainiest, sweatiest days on your skis or snowboard. The jacket itself is cut for movement, with Armada's loose, comfortable, and stylish Standard fit. Together, the powers of GORE-TEX and Armada will take your on-mountain comfort levels to another level!", image:"https://images.evo.com/imgp/zoom/201268/845384/armada-haydon-3l-gore-tex-jacket-.jpg", brand: "Armada", count: 5)



Apparel.create(sku: 2003, name: "TNP Insulated Anorak", price: 230, cost: 150, size: "Large", category: "Jackets", sex: "Men", description: "The Oakley TNP Insulated Anorak is a snow jacket with style. The radness of an old school anorak combines with stretch construction and 80g warmth-trapping synthetic insulation in this pullover coat. It'll keep you warm and dry while you sizzle the slopes with style and play in the powder with confidence in the gear on your body.", image:"https://images.evo.com/imgp/zoom/180756/871670/oakley-tnp-insulated-anorak-.jpg", brand: "Oakley", count: 5)



Apparel.create(sku: 2004, name: "Elevation Infinity Shell", price: 449, cost: 301, size: "Small", category: "Jackets", sex: "Women", description: "The perfect jacket for working from home aka taking your meetings from the lodge and spending the rest of the day on the slopes! With the Helly Hansen Elevation Infinity Shell Jacket, you get a premium 3-layer construction and LIFA® Infinity Pro™ technology you can rely on to keep the elements out even through the gnarliest winter storms. And with the relaxed fit, you're given the freedom to add and subtract layers needed to manage your heat. Top things of with Helly Hansen's proprietary Life Pocket+™ with PrimaLoft® Aerogel insulation to sustain longer battery life and protect your phone from the cold so you can answer emails and make the gondola your new office.", image:"https://images.evo.com/imgp/zoom/203463/835561/helly-hansen-elevation-infinity-shell-jacket-women-s-.jpg", brand: "Helly Hansen", count: 5)



Apparel.create(sku: 2005, name: " Woodland Insulated", price: 249, cost: 180, size: "Small", category: "Jackets", sex: "Men", description: "With the 686 Woodland Insulated Jacket, you get the classic flannel style in a durable waterproof form that's ready for shredding on the slopes. Unlike typical flannels, the Woodland has a breathable-waterproof membrane to keep you from soaking through when you take a spill in the park or get a face shot of blower pow. Plus, it's loaded with thermally mapped synthetic insulation and equipped with a snap-off quilted hood for tons of warmth and versatile style.", image:"https://images.evo.com/imgp/zoom/197662/805498/686-woodland-insulated-jacket-.jpg", brand: "686", count: 5)



Apparel.create(sku: 2006, name: "AK 3L GORE-TEX Freebird", price: 599, cost: 450, size: "Medium", category: "Pants", sex: "Men", description: "When the snow starts nuking nothing beats the Burton AK 3L GORE-TEX Freebird Bib Pants to keep you comfortably shredding all day. Constructed with ultra lightweight 3-layer GORE-TEX fabric, the Freebird Bib Pants bring top end weather protection to a backcountry capable design incorporating stretch panels for mobility on both the hike up and the ride down. Large thigh vents allow you to rapidly dump heat, and an accessible beacon pocket is the perfect solution for anyone struggling with an uncomfortable harness. Uncompromising performance and classic Burton style, the Freebird Bib Pants bring the best of the best to the table.", image:"https://images.evo.com/imgp/zoom/152852/820219/burton-ak-3l-gore-tex-freebird-bib-bibs-.jpg", brand: "Buron", count: 5)



Apparel.create(sku: 2007, name: "Capow Short Bibs", price: 479, cost: 233, size: "Medium", category: "Pants", sex: "Women", description: "Purpose built for backcountry pros, the Trew Gear Capow Short Bibs live for long days in the mountains in search of bottomless pow. Created from a mechanical stretch main fabric with a breathable stretch-woven nylon upper bib, the Capow Bibs provide unrestricted movement for the climbs as well as descents, plus impressive breathability to keep you from overheating during high exertion. Don't let mediocre bibs hold you back, experience unrivaled backcountry performance with the Trew Gear Capow Short Bibs.", image:"https://images.evo.com/imgp/zoom/223095/897590/trew-gear-capow-short-bibs-women-s-.jpg", brand: "Trew", count: 5)



Apparel.create(sku: 2008, name: "PowSlayer", price: 384, cost: 210, size: "Small", category: "Pants", sex: "Women", description: "A new addition to the PowSlayer family, the Patagonia PowSlayer Pants drop the high waist and suspenders (you know better than to fall in pow, right?) but keep the super functional pocket configuration and articulated cut, as well as the top-of-the-line GORE-TEX® Pro 3L fabric which offers the ultimate combination of waterproofing and breathability.", image:"https://images.evo.com/imgp/zoom/136300/767266/patagonia-powslayer-pants-women-s-.jpg", brand: "Patagonia", count: 5)



Apparel.create(sku: 2009, name: "QST 3L Shell", price: 374, cost: 260, size: "Large", category: "Pants", sex: "Men", description: "Do you ski QST? Add to your quiver or kick off your backcountry career in a major way, with the Salomon QST 3L Shell Pants. These ultra durable bib-pants are made for long days on the skin track and off-piste adventures big and small. Their shell design with body adaptable MotionFit™ 360 moves with your body and is ideal for layering, whatever the weather brings. Add on the removable bib for extra customization and high back protection against big plumes of powder.", image:"https://images.evo.com/imgp/zoom/198789/811706/salomon-qst-3l-shell-pants-.jpg", brand: "Saloman" , count: 5)


# ACCESSORIES
Accessory.create(sku: 3000, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggles", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3001, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggles", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3002, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggles", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3003, name: "Smith I​/O MAG ", price: 200, cost: 100, size: "L", category: "Goggles", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178931/713077/smith-i-o-mag-goggles-.jpg", brand: "Smith", count: 5)

Accessory.create(sku: 3004, name: "SmithSarek Ecocuir", price: 150, cost: 75, size: "L", category: "Gloves", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178633/725252/hestra-sarek-ecocuir-gloves-.jpg", brand: "Hestra", count: 5)

Accessory.create(sku: 3005, name: "Sarek Ecocuir", price: 150, cost: 75, size: "L", category: "Gloves", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178633/725252/hestra-sarek-ecocuir-gloves-.jpg", brand: "Hestra", count: 5)

Accessory.create(sku: 3006, name: "Smith I​/O MAG ", price: 150, cost: 75, size: "L", category: "Gloves", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/178633/725252/hestra-sarek-ecocuir-gloves-.jpg", brand: "Hestra", count: 5)

Accessory.create(sku: 3007, name: "SPowder Town Beanie", price: 50, cost: 25, size: "L", category: "Hats", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/103037/857021/patagonia-powder-town-beanie-.jpg", brand: "Patagonia", count: 5)

Accessory.create(sku: 3008, name: "Powder Town Beanie", price: 50, cost: 25, size: "L", category: "Hats", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/103037/857021/patagonia-powder-town-beanie-.jpg", brand: "Patagonia", count: 5)

Accessory.create(sku: 3009, name: "Powder Town Beanie", price: 50, cost: 25, size: "L", category: "Hats", sex: "M", description: "Description jacket goes here.", image:"https://images.evo.com/imgp/zoom/103037/857021/patagonia-powder-town-beanie-.jpg", brand: "Patagonia", count: 5)

# USERS
User.create(username: "jon", password:"jon", email:"jon@jon.com", admin: true)
puts "Seeding Complete"